env:
  es6: true
  browser: true
  commonjs: true

extends:
  [
    "plugin:react/recommended",
    "prettier",
    "plugin:prettier/recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
  ]

parser: "@babel/eslint-parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 6
  sourceType: module

plugins: ["react", "simple-import-sort", "prettier"]

settings:
  react:
    version: "17"
  import/resolver: { "node": { "extensions": [".js", ".jsx", ".native.js"] } }

rules:
  {
    "simple-import-sort/imports": "error",
    "simple-import-sort/exports": "error",
    "prettier/prettier": "error",
    "no-unused-vars": "error",
    "import/extensions": ["error", "never"],
  }
