require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - 'Rakefile'
    - 'config.ru'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'vendor/mimemagic-0.3.5/**/*'
    - 'vendor/bundle/**/*'
    - 'db/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*.rb'
    - 'spec/**/*.rb'

Layout/LineLength:
  Enabled: true
  Max: 160

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5
