finish_competition:
  cron: '0 0 1 * *'  # Monthly at 00:00 on day-of-month 1
  class: FinishCompetitionWorker
clear_entrie_without_users:
  cron: '0 0 * * *'  # Daily at 00:00 each day
  class: ClearEntriesWithoutUsersWorker
